### ISSUE TITLE
_tkinter.TclError: unknown option "-variable"

### ISSUE THREAD

**Issue by spikespaz** [DeflatedPickle/pkinter#14]
```
$ python pkinter_test.py
Traceback (most recent call last):
  File "pkinter_test.py", line 48, in <module>
    statusbar.add_variable(variable=variable)
  File "C:\Users\spike\Documents\github.com\DeflatedPickle\pkinter\pkinter\statusbar.py", line 61, in add_variable
    widget = ttk.Label(self, **kwargs)
  File "C:\Python36\lib\tkinter\ttk.py", line 761, in __init__
    Widget.__init__(self, master, "ttk::label", kw)
  File "C:\Python36\lib\tkinter\ttk.py", line 559, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Python36\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-variable"
```

**Comment by Rafa-s-r** [comment]
I have the same issue. Did you can resolve it?

**Comment by Rafa-s-r** [comment]
I can resolve changing the parameters order,

`    def __init__(self, driver, *args, **kwargs):`

instead using variable=foo when create the object, I pass it like an positional argument.

**Comment by jinai** [comment]
On line 48 replace:
`statusbar.add_variable(variable=variable)`

with:
`statusbar.add_variable(textvariable=variable)`

**Comment by SAROJ66** [comment]
_tkinter.TclError: unknown option "-hight"

Kindly suggest me

**Comment by teriyake** [comment]
> 
> 
> _tkinter.TclError: unknown option "-hight"
> 
> Kindly suggest me

should be 'height'
